import { RoastResult } from '../types';

/**
 * Renders a roast result to a Markdown document suitable for saving to a file.
 */
export function renderToMarkdown(result: RoastResult): string {
  const { roasts, score, stats } = result;
  const lines: string[] = [];

  lines.push(`# 🔥 Git Roast — ${stats.meta.author}`);
  lines.push('');
  lines.push(`**Repo:** \`${stats.meta.repoName}\`  `);
  lines.push(
    `**Period:** ${formatDate(stats.meta.firstCommitDate)} → ${formatDate(stats.meta.lastCommitDate)}  `,
  );
  lines.push(`**Total commits:** ${stats.meta.totalCommits}  `);
  lines.push(`**Active days:** ${stats.patterns.totalActiveDays}`);
  lines.push('');

  lines.push(`## Overall: ${score.level} (${score.overall}/100)`);
  lines.push('');
  lines.push('| Category | Grade | Score |');
  lines.push('| --- | --- | --- |');
  for (const cs of score.categoryScores) {
    lines.push(`| ${cs.label} | ${cs.grade} | ${cs.score}/100 |`);
  }
  lines.push('');

  lines.push('## 🔥 Roasts');
  lines.push('');
  for (const r of roasts) {
    const severity = r.severity.toUpperCase();
    lines.push(`- ${r.emoji} **[${severity}]** ${r.text}`);
  }
  lines.push('');

  lines.push('---');
  lines.push('_Generated by [gitroast](https://github.com/cadzchua/gitroast)._');
  lines.push('');

  return lines.join('\n');
}

function formatDate(date: Date): string {
  return date.toISOString().split('T')[0];
}
