import chalk from 'chalk';
import Table from 'cli-table3';
import { RoastResult, Roast, CategoryScore } from '../types';

/** ASCII art banner for Git Roast */
const BANNER = `
  ${chalk.hex('#FF6B35')('┌─────────────────────────────────────────────┐')}
  ${chalk.hex('#FF6B35')('│')}                                             ${chalk.hex('#FF6B35')('│')}
  ${chalk.hex('#FF6B35')('│')}   ${chalk.bold.hex('#FF4500')('🔥  G I T   R O A S T  🍖')}              ${chalk.hex('#FF6B35')('│')}
  ${chalk.hex('#FF6B35')('│')}   ${chalk.dim('Brutally honest Git analysis')}              ${chalk.hex('#FF6B35')('│')}
  ${chalk.hex('#FF6B35')('│')}                                             ${chalk.hex('#FF6B35')('│')}
  ${chalk.hex('#FF6B35')('└─────────────────────────────────────────────┘')}
`;

/** Level-specific colors and emojis */
const LEVEL_STYLES: Record<string, { color: string; emoji: string }> = {
  'Golden Developer': { color: '#FFD700', emoji: '👑' },
  'Decent Human': { color: '#4CAF50', emoji: '👍' },
  'Chaotic Neutral': { color: '#FF9800', emoji: '🎲' },
  'Code Gremlin': { color: '#FF5722', emoji: '👹' },
  'Absolute Menace': { color: '#B71C1C', emoji: '💀' },
};

/** Severity-specific colors */
const SEVERITY_COLORS: Record<string, string> = {
  savage: '#FF1744',
  medium: '#FF9100',
  mild: '#FFEA00',
};

/**
 * Renders the full roast result to the terminal.
 */
export function renderToTerminal(result: RoastResult): void {
  const { roasts, score, stats } = result;

  // Banner
  console.log(BANNER);

  // Stats header
  console.log(
    chalk.cyan.bold('  📊 Stats for: ') +
      chalk.white.bold(stats.meta.author) +
      chalk.dim(' @ ') +
      chalk.white.bold(stats.meta.repoName),
  );
  console.log(
    chalk.dim(
      `     Total Commits: ${stats.meta.totalCommits} | ` +
        `First: ${formatDate(stats.meta.firstCommitDate)} | ` +
        `Last: ${formatDate(stats.meta.lastCommitDate)} | ` +
        `Active Days: ${stats.patterns.totalActiveDays}`,
    ),
  );
  console.log();

  // Score table
  renderScoreTable(score.categoryScores);
  console.log();

  // Overall level
  const levelStyle = LEVEL_STYLES[score.level] || LEVEL_STYLES['Chaotic Neutral'];
  console.log(
    chalk.bold(
      `  🏆 Overall: ${levelStyle.emoji} ` +
        chalk.hex(levelStyle.color)(score.level.toUpperCase()) +
        chalk.dim(` (${score.overall}/100)`),
    ),
  );
  console.log();

  // Separator
  console.log(chalk.hex('#FF6B35')('  ═══════════════════════════════════════════'));
  console.log();

  // Roasts
  console.log(chalk.red.bold('  🔥 YOUR ROASTS:\n'));

  for (const roast of roasts) {
    renderRoast(roast);
  }

  // Footer
  console.log();
  console.log(
    chalk.dim('  ─────────────────────────────────────────────'),
  );
  console.log(
    chalk.dim('  Generated by ') +
      chalk.hex('#FF6B35').bold('gitroast') +
      chalk.dim(' • https://github.com/cadzchua/gitroast'),
  );
  console.log(
    chalk.dim('  Star ⭐ the repo if this made you laugh (or cry)'),
  );
  console.log();
}

/** Renders the score table */
function renderScoreTable(categoryScores: CategoryScore[]): void {
  const table = new Table({
    head: [
      chalk.bold.white('Category'),
      chalk.bold.white('Grade'),
      chalk.bold.white('Score'),
    ],
    colWidths: [22, 10, 12],
    style: {
      head: [],
      border: ['gray'],
      compact: true,
    },
    chars: {
      top: '─',
      'top-mid': '┬',
      'top-left': '  ┌',
      'top-right': '┐',
      bottom: '─',
      'bottom-mid': '┴',
      'bottom-left': '  └',
      'bottom-right': '┘',
      left: '  │',
      'left-mid': '  ├',
      mid: '─',
      'mid-mid': '┼',
      right: '│',
      'right-mid': '┤',
      middle: '│',
    },
  });

  const categoryEmojis: Record<string, string> = {
    Timing: '⏰',
    Messages: '💬',
    Patterns: '📈',
    Files: '📁',
  };

  for (const cs of categoryScores) {
    const emoji = categoryEmojis[cs.label] || '📊';
    const gradeColor = getGradeColor(cs.grade);

    table.push([
      `${emoji} ${cs.label}`,
      chalk.hex(gradeColor).bold(cs.grade),
      `${colorizeScore(cs.score)}/100`,
    ]);
  }

  console.log(table.toString());
}

/** Renders a single roast card */
function renderRoast(roast: Roast): void {
  const color = SEVERITY_COLORS[roast.severity] || SEVERITY_COLORS.medium;
  const severityLabel =
    roast.severity === 'savage'
      ? chalk.red(' [SAVAGE]')
      : roast.severity === 'medium'
        ? chalk.yellow(' [MEDIUM]')
        : chalk.dim(' [MILD]');

  console.log(
    `  ${roast.emoji} ` + chalk.hex(color)(roast.text) + severityLabel,
  );
  console.log();
}

/** Returns a color hex based on grade */
function getGradeColor(grade: string): string {
  if (grade.startsWith('A')) return '#4CAF50';
  if (grade.startsWith('B')) return '#8BC34A';
  if (grade.startsWith('C')) return '#FF9800';
  if (grade.startsWith('D')) return '#FF5722';
  return '#B71C1C';
}

/** Colors a numeric score based on value */
function colorizeScore(score: number): string {
  if (score >= 80) return chalk.green(score.toString());
  if (score >= 60) return chalk.hex('#8BC34A')(score.toString());
  if (score >= 40) return chalk.yellow(score.toString());
  if (score >= 20) return chalk.hex('#FF5722')(score.toString());
  return chalk.red(score.toString());
}

/** Formats a Date to a readable string */
function formatDate(date: Date): string {
  const months = [
    'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
    'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec',
  ];
  return `${months[date.getMonth()]} ${date.getDate()}, ${date.getFullYear()}`;
}
